name: refugee_dashboard
description: "Refugee care admin dashboard app"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  fl_chart: ^0.69.2
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  go_router: ^14.1.1
  google_fonts: ^6.2.1
  hooks_riverpod: ^2.5.2
  flutter_hooks: ^0.20.5
  riverpod_annotation: ^2.3.5
  freezed: ^2.5.2
  freezed_annotation: ^2.4.4
  firebase_core: ^3.7.0
  firebase_messaging: ^15.1.3
  image_picker: ^1.1.2
  file_picker: ^8.0.0+1
  hive: any
  hive_flutter: ^1.1.0
  get_it: ^8.0.0
  http: ^1.2.1
  # appwrite:
  #   path: /Users/vanzarlyanhtan/VSCode Projects/refugee_care_mobile/app-write-sdk

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  riverpod_generator: ^2.4.0
  custom_lint: ^0.7.0
  riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/images/illustration/
    - assets/logo/
